apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nmt3atij1-nodejs 
  janus-idp.io/tekton: nmt3atij1-nodejs
  backstage.io/kubernetes-id: nmt3atij1-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nmt3atij1-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  